<?xml version="1.0"?>
<package format="3">
  <name>spacewire_pc</name>
  <version>0.0.0</version>
  <description>PC-side launch and diagnostics for the SpaceWire demonstrator</description>

  <maintainer email="arthurlenders@hotmail.com">4rthrl</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>launch</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>diagnostic_aggregator</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
